using System;

namespace ModuleFourAssignment
{
    public class Program
    {
        public static void Main(string[] args)
        {
        }

        #region Structs

        public struct Student
        {
            #region Members

            //Public members is really gross and not proper encapsulation just FYI

            public string FirstName;
            public string LastName;
            public DateTime Birthday;
            public string Address;
            public string Address1;
            public string City;
            public State State;
            public string Zip;
            public Country Country;
            public string Notes;

            #endregion Members

            public Student(string fName, string lName, DateTime bDay, string address, string address1, 
                           string city, State state, string zip, Country country, string notes) : this()
            {
                FirstName = fName;
                LastName = lName;
                Birthday = bDay;
                Address = address;
                Address1 = address1;
                City = city;
                State = state;
                Zip = zip;
                Country = country;
                Notes = notes;
            }
        }


        #endregion Structs

        #region Enums

        public enum State
        {
            AL,
            AK,
            AZ,
            AR,
            CA,
            CO,
            CT,
            DE,
            FL,
            GA,
            HI,
            ID,
            IL,
            IN,
            IA,
            KS,
            KY,
            LA,
            ME,
            MD,
            MA,
            MI,
            MN,
            MS,
            MO,
            MT,
            NE,
            NV,
            NH,
            NJ,
            NM,
            NY,
            NC,
            ND,
            OH,
            OK,
            OR,
            PA,
            RI,
            SC,
            SD,
            TN,
            TX,
            UT,
            VT,
            VA,
            WA,
            WV,
            WI,
            WY,
            NonUS
        }

        public enum Country
        {
            AFG,
            ALB,
            DZA,
            ASM,
            AND,
            AGO,
            AIA,
            ATA,
            ATG,
            ARG,
            ARM,
            ABW,
            AUS,
            AUT,
            AZE,
            BHS,
            BHR,
            BGD,
            BRB,
            BLR,
            BEL,
            BLZ,
            BEN,
            BMU,
            BTN,
            BOL,
            BIH,
            BWA,
            BVT,
            BRA,
            IOT,
            BRN,
            BGR,
            BFA,
            BDI,
            KHM,
            CMR,
            CAN,
            CPV,
            CYM,
            CAF,
            TCD,
            CHL,
            CHN,
            CXR,
            CCK,
            COL,
            COM,
            COG,
            COD,
            COK,
            CRI,
            CIV,
            HRV,
            CUB,
            CYP,
            CZE,
            DNK,
            DJI,
            DMA,
            DOM,
            TMP,
            ECU,
            EGY,
            SLV,
            GNQ,
            ERI,
            EST,
            ETH,
            FLK,
            FRO,
            FJI,
            FIN,
            FRA,
            FXX,
            GUF,
            PYF,
            ATF,
            GAB,
            GMB,
            GEO,
            DEU,
            GHA,
            GIB,
            GRC,
            GRL,
            GRD,
            GLP,
            GUM,
            GTM,
            GIN,
            GNB,
            GUY,
            HTI,
            HMD,
            VAT,
            HND,
            HKG,
            HUN,
            ISL,
            IND,
            IDN,
            IRN,
            IRQ,
            IRL,
            ISR,
            ITA,
            JAM,
            JPN,
            JOR,
            KAZ,
            KEN,
            KIR,
            PRK,
            KOR,
            KWT,
            KGZ,
            LAO,
            LVA,
            LBN,
            LSO,
            LBR,
            LBY,
            LIE,
            LTU,
            LUX,
            MAC,
            MKD,
            MDG,
            MWI,
            MYS,
            MDV,
            MLI,
            MLT,
            MHL,
            MTQ,
            MRT,
            MUS,
            MYT,
            MEX,
            FSM,
            MDA,
            MCO,
            MNG,
            MNE,
            MSR,
            MAR,
            MOZ,
            MMR,
            NAM,
            NRU,
            NPL,
            NLD,
            ANT,
            NCL,
            NZL,
            NIC,
            NER,
            NGA,
            NIU,
            NFK,
            MNP,
            NOR,
            OMN,
            PAK,
            PLW,
            PAN,
            PNG,
            PRY,
            PER,
            PHL,
            PCN,
            POL,
            PRT,
            PRI,
            QAT,
            REU,
            ROM,
            RUS,
            RWA,
            KNA,
            LCA,
            VCT,
            WSM,
            SMR,
            STP,
            SAU,
            SEN,
            SRB,
            SYC,
            SLE,
            SGP,
            SVK,
            SVN,
            SLB,
            SOM,
            ZAF,
            SSD,
            SGS,
            ESP,
            LKA,
            SHN,
            SPM,
            SDN,
            SUR,
            SJM,
            SWZ,
            SWE,
            CHE,
            SYR,
            TWN,
            TJK,
            TZA,
            THA,
            TGO,
            TKL,
            TON,
            TTO,
            TUN,
            TUR,
            TKM,
            TCA,
            TUV,
            UGA,
            UKR,
            ARE,
            GBR,
            USA,
            UMI,
            URY,
            UZB,
            VUT,
            VEN,
            VNM,
            VGB,
            VIR,
            WLF,
            ESH,
            YEM,
            ZMB,
            ZWE
        }

        #endregion Enums
    }
}
